from pathlib import Path
from datetime import datetime
import pandas as pd
from docx import Document
from docx.shared import Pt

ROOT      = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
OUTPUT    = ROOT / "data" / "output"
OUTPUT.mkdir(parents=True, exist_ok=True)


def fmt(value):
    return f"{value:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def load_data():
    watchlist         = pd.read_parquet(PROCESSED / "watchlist_topics.parquet")
    ikpa_leading      = pd.read_csv(PROCESSED / "topic_ikpa_best_lag.csv")
    realisasi_leading = pd.read_csv(PROCESSED / "topic_realisasi_best_lag.csv")
    risk_file         = next(PROCESSED.glob("risk*.parquet"), None)
    if risk_file is None:
        raise FileNotFoundError("Risk monitor parquet not found.")
    risk = pd.read_parquet(risk_file)
    return watchlist, ikpa_leading, realisasi_leading, risk


def build_docx(watchlist, ikpa_leading, realisasi_leading, risk):
    doc           = Document()
    top_watchlist = watchlist.iloc[0]
    top_ikpa      = ikpa_leading.iloc[0]
    top_realisasi = realisasi_leading.iloc[0]
    red_count     = risk["risk_level"].eq("RED").sum()
    yellow_count  = risk["risk_level"].eq("YELLOW").sum()
    green_count   = risk["risk_level"].eq("GREEN").sum()
    periode_awal  = risk["periode"].min()
    periode_akhir = risk["periode"].max()
    top5_topics   = ", ".join(watchlist.head(5)["topic"].tolist())

    # Title
    title = doc.add_heading("Fiscal Service Intelligence", level=0)
    title.alignment = 1
    p = doc.add_paragraph()
    p.alignment = 1
    p.add_run("Executive Brief\n").bold = True
    p.runs[0].font.size = Pt(14)
    p.add_run(f"Tanggal Laporan: {datetime.now().strftime('%d %B %Y')}")
    doc.add_paragraph("Generated by Fiscal Service Intelligence (FSI)")
    doc.add_paragraph("Data Source: HAI DJPb, IKPA, Realisasi Anggaran")
    doc.add_page_break()

    # 1. Ringkasan Eksekutif
    doc.add_heading("1. Ringkasan Eksekutif", level=1)
    doc.add_paragraph(f"Periode Analisis: {periode_awal} s.d. {periode_akhir}")
    doc.add_paragraph(
        f"Fiscal Service Intelligence (FSI) memanfaatkan data layanan HAI DJPb "
        f"untuk mengidentifikasi pola permasalahan pelaksanaan anggaran, "
        f"mengukur kompleksitas layanan, serta mendeteksi potensi risiko "
        f"yang dapat mempengaruhi kualitas pelaksanaan anggaran. "
        f"Berdasarkan hasil analisis, topik prioritas tertinggi saat ini adalah "
        f"{top_watchlist['topic']} dengan Watchlist Score {fmt(top_watchlist['watchlist_score'])}."
    )
    doc.add_paragraph(f"Topik prioritas saat ini meliputi: {top5_topics}.")

    # 2. Early Warning Watchlist
    doc.add_heading("2. Early Warning Watchlist", level=1)
    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "Rank", "Topic", "Score", "Priority"
    for idx, row in watchlist.head(10).iterrows():
        cells = table.add_row().cells
        cells[0].text = str(idx + 1)
        cells[1].text = str(row["topic"])
        cells[2].text = fmt(row["watchlist_score"])
        cells[3].text = str(row["priority"])
    doc.add_paragraph()

    # 3. Leading Indicator Analysis
    doc.add_heading("3. Leading Indicator Analysis", level=1)
    doc.add_paragraph(
        f"Topik dengan hubungan terkuat terhadap IKPA adalah {top_ikpa['topic']} "
        f"dengan korelasi {top_ikpa['correlation']:.3f} dan lag {top_ikpa['lag']} bulan."
    )
    doc.add_paragraph(
        f"Topik dengan hubungan terkuat terhadap realisasi anggaran adalah {top_realisasi['topic']} "
        f"dengan korelasi {top_realisasi['correlation']:.3f} dan lag {top_realisasi['lag']} bulan."
    )

    # 4. Risk Monitoring
    doc.add_heading("4. Risk Monitoring", level=1)
    doc.add_paragraph(
        f"Distribusi risiko selama periode analisis:\n"
        f"GREEN: {green_count}  |  YELLOW: {yellow_count}  |  RED: {red_count}"
    )

    # 5. Key Findings
    doc.add_heading("5. Key Findings", level=1)
    for item in [
        f"Topik {top_watchlist['topic']} merupakan prioritas pembinaan tertinggi berdasarkan kombinasi indikator emerging issues, complexity, dan impact.",
        f"Topik {top_ikpa['topic']} memiliki hubungan negatif terkuat terhadap kualitas pelaksanaan anggaran (IKPA).",
        f"Topik {top_realisasi['topic']} berpotensi mempengaruhi realisasi anggaran dalam kurun waktu {top_realisasi['lag']} bulan.",
        "Data layanan HAI DJPb dapat dimanfaatkan sebagai early warning system pelaksanaan anggaran.",
    ]:
        doc.add_paragraph(item, style="List Bullet")

    # 6. Recommendations
    doc.add_heading("6. Recommendations", level=1)
    for item in [
        f"Prioritaskan pembinaan pada topik {top_watchlist['topic']}.",
        "Fokuskan monitoring pada topik yang memiliki hubungan kuat dengan IKPA dan realisasi.",
        "Manfaatkan Early Warning Watchlist sebagai dasar penentuan prioritas pembinaan.",
        "Gunakan data HAI DJPb sebagai sumber informasi strategis dalam pengambilan keputusan.",
    ]:
        doc.add_paragraph(item, style="List Number")

    output_file = OUTPUT / "executive_brief.docx"
    doc.save(output_file)
    return output_file


def main():
    print("\nLoading datasets...")
    watchlist, ikpa_leading, realisasi_leading, risk = load_data()

    print("Building executive brief DOCX...")
    output_file = build_docx(watchlist, ikpa_leading, realisasi_leading, risk)

    print("\n=================================")
    print("EXECUTIVE BRIEF GENERATED")
    print(output_file)
    print("=================================")


if __name__ == "__main__":
    main()